# Base image for ubuntu 14.04
FROM iodigital/ubuntu-node:v1
MAINTAINER io <devops@io.co.za>

ENV AUTHED_KEYS_FILE /home/node/.ssh/authorized_keys
ENV APP_FOLDER_PATH /var/goddard/apps/

VOLUME ["/var/goddard/apps", "/home/node/.ssh"]